In [ ]:
!pip install transformers[tokenizers]

from transformers import AutoTokenizer, AutoModelForSequenceClassification

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 15.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 37.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 30.2 MB/s eta 0:00:00


In [ ]:
import transformers

model = transformers.AutoModelForSequenceClassification.from_pretrained("google/electra-base-discriminator")

# Tokenize the text data
tokenizer = transformers.AutoTokenizer.from_pretrained("google/electra-base-discriminator")
inputs = tokenizer(text="The quick brown fox jumps over the lazy dog. The dog is sleeping.", return_tensors="pt")

# Classify the sequence
outputs = model(**inputs)

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at google/electra-base-discriminator and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs['logits']

tensor([[-0.0014,  0.1174]], grad_fn=<AddmmBackward0>)

In [ ]:
# Get the classification prediction for each sentence
sentence_classification_predictions = outputs["logits"].squeeze(-1)

# Print the classification predictions for each sentence
for i, sentence_classification_prediction in enumerate(sentence_classification_predictions):
    print(f"Sentence {i + 1}: {sentence_classification_prediction}")

Sentence 1: tensor([-0.0014,  0.1174], grad_fn=<UnbindBackward0>)


In [ ]:
outputs['logits']

tensor([[-0.0014,  0.1174]], grad_fn=<AddmmBackward0>)

In [ ]:
sentence_classification_predictions

tensor([[-0.0014,  0.1174]], grad_fn=<SqueezeBackward1>)

In [ ]:
import torch

torch.sigmoid(outputs['logits'])

tensor([[0.4997, 0.5293]], grad_fn=<SigmoidBackward0>)